name: Deploy to Vercel

on:
  push:
    branches:
      - main   # or dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Vercel
        run: npm install -g vercel

      - name: Pull env
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
